config/routes.rb
Rails.application.routes.draw do

  resources :notifications , except: [:destroy, :edit, :update]
  resources :employees
  resources :activities
  resources :products
  resources :schedulings do
    collection do
      get 'todaypending'
      get 'today'
    end
  end

  resources :documents  do 
    collection do
      get 'pending'
      get 'payed'
      get 'with_received'
    end
  end  
  resources :acquittances do
    collection do
      get 'today'
    end
  end

  authenticated :user do
    resources :entities, only: [:new, :create, :edit, :update, :destroy]
    root to: 'entities#index', as: :authenticated_root
  end
  resources :entities, only: [:index, :show]
  root to: redirect('/users/sign_in')


  devise_for :users, 
  :controllers => { registrations: 'registrations' }, 
  :path_names => {:sign_up => 'register'}
  devise_scope :user do
    get "users/register(/:entity_id)", :to => "registrations#new", as: :new_entity_user
  end


  # controller :registrations do 
  # end
  controller :employees do 
    get 'employees/new(/:entity_id)' => :new, as: :new_entity_employee
  end
  controller :documents do 
    get 'documents/new(/:scheduling_id)' => :new, as: :new_scheduling_document
  end
  controller :acquittances do 
    get 'acquittances/new(/:document_id)' => :new, as: :new_document_acquittance
  end
  controller :notifications do 
    get 'schedulings/:scheduling_id/notifications/new' => :new, as: :new_scheduling_notification
    get 'notifications/:id/resend/' => :resend, as: :notification_resend
  end


end

app/models/acquittance.rb
class Acquittance < ActiveRecord::Base
  belongs_to :document

  validates :document_id, presence: true
  validates :gross_value, presence: true, :numericality => true
  validates :discount_value, :numericality => {:greater_than_or_equal_to => 0}
  validate :valid_value, on: [:create, :update]

  default_scope { order(id: :desc) }
  scope :today, ->{where("DATE(created_at) = DATE(NOW())")}

  def valid_value 
  	pending_value = self.document.get_pending_value
  	received_value = self.document.get_received_value
  	if pending_value <= 0 && self.gross_value >= 0
    	errors.add(:gross_value, 'This document already was full payed') 
    elsif received_value + self.gross_value < 0 
    	errors.add(:gross_value, "Can't reverse document with no acquittances") 
    elsif self.gross_value > pending_value
    	self.gross_value =  pending_value
    	self.liquid_value = self.gross_value - self.discount_value
    end	
	end

  def load_from_document(document)
    self.document = document
    self.gross_value = document.get_pending_value
    self.discount_value = 0	
    self.liquid_value = self.gross_value
  end

  def get_reversed 
    acquittance = Acquittance.new
    acquittance.document_id = self.document_id
    acquittance.gross_value = self.gross_value * -1 
    acquittance.discount_value = 0
    acquittance.liquid_value = acquittance.gross_value
    acquittance.observation = "Reverse acquittance"
    acquittance.reference_code = self.id
    return acquittance
  end
end

app/controllers/acquittances_controller.rb
class AcquittancesController < ApplicationController
  before_action :set_acquittance, only: [:show, :edit, :update, :destroy]

  # GET /acquittances
  # GET /acquittances.json
  def index
    @acquittances = Acquittance.all
    @active_all = "active"
  end
  def today
    @acquittances = Acquittance.today
    @active_today = "active"
    render action: :index
  end

  # GET /acquittances/1
  # GET /acquittances/1.json
  def show
  end

  # GET /acquittances/new
  def new
    @acquittance = Acquittance.new
    if params[:document_id]
      @acquittance.load_from_document(Document.find(params[:document_id]))
    else
      @acquittance.document = Document.new
    end
    @pending = Document.pending
  end

  # GET /acquittances/1/edit
  def edit
  end

  # POST /acquittances
  # POST /acquittances.json
  def create
    @acquittance = Acquittance.new(acquittance_params)

    respond_to do |format|
      if @acquittance.save
        format.html { redirect_to @acquittance, notice: 'Acquittance was successfully created.' }
        format.json { render :show, status: :created, location: @acquittance }
      else
        format.html { render :new }
        format.json { render json: @acquittance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acquittances/1
  # PATCH/PUT /acquittances/1.json
  def update
    respond_to do |format|
      if @acquittance.update(acquittance_params)
        format.html { redirect_to @acquittance, notice: 'Acquittance was successfully updated.' }
        format.json { render :show, status: :ok, location: @acquittance }
      else
        format.html { render :edit }
        format.json { render json: @acquittance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acquittances/1
  # DELETE /acquittances/1.json
  def destroy
    @reverse = @acquittance.get_reversed 
    respond_to do |format|
      if @reverse.save
        format.html { redirect_to @reverse, notice: "The Acquittance #{@acquittance.id} was successfully reversed." }
        format.json { render :show, status: :created, location: @acquittance }
      else
        format.html { render :new }
        format.json { render json: @acquittance.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acquittance
      @acquittance = Acquittance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acquittance_params
      params.require(:acquittance).permit(:document_id, :gross_value, :discount_value, :liquid_value, :reference_code, :observation)
    end
end

app/helpers/acquittances_helper.rb
module AcquittancesHelper
end

app/views/acquittances/_form.html.erb
<%= simple_form_for @acquittance, :html => { :class => 'form-horizontal' } do |f| %>
<div class="form-group">
  <div class="col-md-12">
    <div class="panel panel-warning">
      <div class="panel-heading">
        Document Info
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <%= f.association :document, autofocus: true, required: true, :value_method => :id, :label_method => :id, :input_html => {:id => "document", :class => "form-control" }  %>
            <%= error_span(@acquittance[:document_id]) %>
          </div>
          <div class="col-md-2">
            <%= link_to "List", documents_path, :class => 'btn btn-default btn-new-resource' %> 
          </div>
          <div class="col-md-6">
            <%= label_tag "Entity", nil, class: '' %>
            <%= label_tag (@acquittance.document.new_record? ? nil : @acquittance.document.entity.name), nil, class: 'form-control', :readonly => "readonly", id: "document-entity" %>
          </div>
          <div class="col-md-4">
            <%= label_tag "Document Value", nil, class: '' %>
            <%= label_tag @acquittance.document.final_value, nil, class: 'form-control', :readonly => "readonly", id: "document-value" %>
          </div>
          <div class="col-md-4">
            <%= label_tag "Received Value", nil, class: '' %>
            <%= label_tag @acquittance.document.get_received_value, nil, class: 'form-control', :readonly => "readonly", id: "document-received" %>
          </div>
          <div class="col-md-4">
            <%= label_tag "Pending Value", nil, class: '' %>
            <%= label_tag @acquittance.document.get_pending_value, nil, class: 'form-control', :readonly => "readonly", id: "document-pending" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="form-group">
  <div class="col-md-4">

    <%= f.input :gross_value, :input_html => {:id => "gross-value", :class => "values form-control", value: f.object.gross_value || '0', min: 0 }   %>
    <%= error_span(@acquittance[:gross_value]) %>
  </div>
  <div class="col-md-4">

    <%= f.input :discount_value, :input_html => {:id => "discount-value", :class => "values form-control", value: f.object.discount_value || '0', min: 0 }   %>
    <%= error_span(@acquittance[:discount_value]) %>
  </div>
  <div class="col-md-4">

    <%= f.input :liquid_value, :input_html => {:id => "liquid-value", :class => "form-control", value: f.object.liquid_value || '0', min: 0, :readonly => "readonly" } %>
    <%= error_span(@acquittance[:liquid_value]) %>

  </div>
</div>
<div class="form-group">
  <div class="col-lg-6">

    <%= f.input :reference_code, :input_html => {:class => 'form-control'} %>
    <%= error_span(@acquittance[:reference_code]) %>
  </div>
</div>
<div class="form-group">
  <div class="col-lg-6">

    <%= f.input :observation, :input_html => {:class => 'form-control'} %>
    <%= error_span(@acquittance[:observation]) %>
  </div>
</div>
<div class="form-group">
  <div class="col-lg-6">

    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    acquittances_path, :class => 'btn btn-default' %>
  </div>
</div>

<% end %>


<script>
$(document).ready(function(){
  $('#document').on('change', function () {
    var element = $(this);

    $.ajax({
      type: 'GET',
      remote: true,
      url: '/documents/' + element.val(),
      success: function(data){
        $('#gross-value').val(data.get_pending_value);
        calculateValues();
        console.log(data);
        $("#document-entity").html(data.entity.name);
        $("#document-value").html(data.final_value);
        $("#document-received").html(data.get_received_value);
        $("#document-pending").html(data.get_pending_value);
      },
      error: function(data){
        console.log('error: ' + data);
        $("#document-id").val("");
        $("#document-info").html("");
      },
      dataType: 'JSON'
    });
  });

  $('.values').on('change', function () {
    calculateValues();
  });

  function calculateValues(){
    liquid = $('#gross-value').val() - $('#discount-value').val();
    if (liquid >= 0) {
      $('#liquid-value').val($('#gross-value').val() - $('#discount-value').val());
    } else {
      $('#liquid-value').val($('#gross-value').val());
      $('#discount-value').val(0);
    };
  }
  
  calculateValues();

});
</script>

app/views/acquittances/_menu.html.erb
<div class="page-header row">
  <div  class="page-title col-sm-12 col-md-3">
    <h3><%=t '.title', :default => title, :model => model_name %></h3>
  </div>
  <div class="col-sm-6 col-md-4 btn-group" role="group">
    <span class="btn disabled">Options</span>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_acquittance_path, :class => 'btn btn-primary' unless action == "new"%>

    <%= link_to t('.list', :default => t("list")),
    acquittances_path, :class => 'btn btn-default' unless action == "index" %>
    <%= link_to t('.reverse', :default => t("helpers.links.reverse")),
                      acquittance_path(@acquittance),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger'  if action == "show"   %>

  </div>
  <% if action == "index" %>
  <div class="col-sm-6 col-md-5">
    <nav>
      <ul class="nav nav-justified">
        <li class="<%= @active_all %>"><a href="<%= acquittances_path %>">All</a></li>
        <li class="<%= @active_today %>"><a href="<%= today_acquittances_path %>">Today</a></li>
      </ul>
    </nav>
  </div>
  <% end %>

</div>

app/views/acquittances/edit.html.erb
<%- model_class = Acquittance -%>
<%= render "menu", action: "edit", title: [:'helpers.titles.edit', 'Edit %{model}'], :model_name => model_class.model_name.human.titleize  %>

<%= render :partial => 'form' %>

app/views/acquittances/index.html.erb
<%- model_class = Acquittance -%>
<%= render "menu", action: "index", title: model_class.model_name.human.pluralize.titleize, model_name: model_class %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:document_id) %></th>
      <th><%= model_class.human_attribute_name(:gross_value) %></th>
      <th><%= model_class.human_attribute_name(:discount_value) %></th>
      <th><%= model_class.human_attribute_name(:liquid_value) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
  </thead>
  <tbody>
    <% @acquittances.each do |acquittance| %>
      <tr>
        <td><%= link_to acquittance.id, acquittance_path(acquittance), :class => 'btn btn-xs btn-default'  %></td>
        <td><%= link_to acquittance.document_id, document_path(acquittance.document), :class => 'btn btn-xs btn-warning'  %></td>
        <td><%= acquittance.gross_value %></td>
        <td><%= acquittance.discount_value %></td>
        <td><%= acquittance.liquid_value %></td>
        <td><%=l acquittance.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/acquittances/new.html.erb
<%- model_class = Acquittance -%>
<%= render "menu", action: "new", title: [:'helpers.titles.new', 'New %{model}'], :model_name => model_class.model_name.human.titleize  %>
<%= render :partial => 'form' %>

app/views/acquittances/show.html.erb
<%- model_class = Acquittance -%>
<%= render "menu", action: "show", title: model_class.model_name.human.titleize, :model_name => model_class.model_name.human.titleize  %>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:document_id) %>:</strong></dt>
  <dd><%= @acquittance.document_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gross_value) %>:</strong></dt>
  <dd><%= @acquittance.gross_value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount_value) %>:</strong></dt>
  <dd><%= @acquittance.discount_value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:liquid_value) %>:</strong></dt>
  <dd><%= @acquittance.liquid_value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reference_code) %>:</strong></dt>
  <dd><%= @acquittance.reference_code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:observation) %>:</strong></dt>
  <dd><%= @acquittance.observation %></dd>
</dl>