config/routes.rb
Rails.application.routes.draw do

  resources :notifications , except: [:destroy, :edit, :update]
  resources :employees
  resources :activities
  resources :products
  resources :schedulings do
    collection do
      get 'todaypending'
      get 'today'
    end
  end

  resources :documents  do 
    collection do
      get 'pending'
      get 'payed'
      get 'with_received'
    end
  end  
  resources :acquittances do
    collection do
      get 'today'
    end
  end

  authenticated :user do
    resources :entities, only: [:new, :create, :edit, :update, :destroy]
    root to: 'entities#index', as: :authenticated_root
  end
  resources :entities, only: [:index, :show]
  root to: redirect('/users/sign_in')


  devise_for :users, 
  :controllers => { registrations: 'registrations' }, 
  :path_names => {:sign_up => 'register'}
  devise_scope :user do
    get "users/register(/:entity_id)", :to => "registrations#new", as: :new_entity_user
  end


  # controller :registrations do 
  # end
  controller :employees do 
    get 'employees/new(/:entity_id)' => :new, as: :new_entity_employee
  end
  controller :documents do 
    get 'documents/new(/:scheduling_id)' => :new, as: :new_scheduling_document
  end
  controller :acquittances do 
    get 'acquittances/new(/:document_id)' => :new, as: :new_document_acquittance
  end
  controller :notifications do 
    get 'schedulings/:scheduling_id/notifications/new' => :new, as: :new_scheduling_notification
    get 'notifications/:id/resend/' => :resend, as: :notification_resend
  end


end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :entity
  belongs_to :scheduling
  before_create :validate_values

  has_many :document_activities
  has_many :activities, through: :document_activities
  accepts_nested_attributes_for :document_activities, reject_if: :all_blank, allow_destroy: true
  has_many :document_products 
  has_many :products, through: :document_products
  accepts_nested_attributes_for :document_products, reject_if: :all_blank, allow_destroy: true

  has_many :acquittances 

  enum operation: {'Sale' => 1, 'Purchase' => 2}

  validates :entity_id, presence: true
  validates :total_value, presence: true, :numericality => {:greater_than => 0 }
  validates :discount_value, :numericality => {:less_than_or_equal_to => :total_value }

  default_scope { order(id: :desc) }
  scope :pending, ->{having(
      'SUM(acquittances.gross_value) < (documents.total_value - documents.discount_value) OR SUM(acquittances.gross_value) IS NULL')}
  scope :payed, ->{having(
      'SUM(acquittances.gross_value) >= (documents.total_value - documents.discount_value)')}
  scope :with_status, ->{select("documents.*", 
      "SUM(acquittances.gross_value) as received_value", 
      "COUNT(acquittances.document_id) as quantity").joins(
      "LEFT JOIN acquittances ON acquittances.document_id = documents.id").group("documents.id")}
=begin

SELECT "documents"."id", 
  documents.total_value - documents.discount_value as final_v, 
  SUM(acquittances.gross_value) as received_v, 
  COUNT(acquittances.document_id) as quantity 
FROM "documents" 
  INNER JOIN "acquittances" ON "acquittances"."document_id" = "documents"."id" 
GROUP BY documents.id

=end

  #scope :payed, ->{joins(:acquittances).where() group('documents.id')}

  def validate_values
    if not self.total_value > 0 
      self.total_value = 0
    end
  	if self.discount_value == nil
  		self.discount_value = 0;
  	elsif self.total_value - self.discount_value < 0
  		self.discount_value = self.total_value 
  	end
  end

  def load_from_scheduling(scheduling)
    self.scheduling = scheduling
    self.scheduling_id = scheduling.id
    self.entity_id = scheduling.entity_id
    self.discount_value = 0
    self.total_value = scheduling.activity.value

    docAct = DocumentActivity.new(
      activity_id: scheduling.activity_id, 
      employee_id: scheduling.employee_id,
      unit_value: scheduling.activity.value,
      quantity: 1
    )

    self.document_activities.append(docAct)
  end

  def scheduling_date
    if self.scheduling
      self.scheduling.dtt_moment.strftime('%d/%m/%Y %H:%I')
    else
      nil
    end 
  end

  def final_value
    self.total_value - self.discount_value unless self.new_record?
  end

  def get_pending_value 
    self.final_value - self.get_received_value unless self.new_record?
  end

  def get_received_value
    self.acquittances.sum(:gross_value) unless self.new_record?
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.with_status
    @active_all = "active"
  end
  def pending
    @documents = Document.with_status.pending
    @active_pending = "active"
    render action: :index
  end
  
  def payed
    @documents = Document.with_status.payed
    @active_payed = "active"
    render action: :index
  end
  def with_received
    @documents = Document.with_status
    render action: :with_received
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    respond_to do |format|
      format.html
      format.json {render json: @document, :include => :entity, :methods => [:final_value, :get_pending_value, :get_received_value], :root => false}
    end
  end

  # GET /documents/new
  def new
    @document = Document.new
    if params[:scheduling_id]
      @document.load_from_scheduling(Scheduling.find(params[:scheduling_id]))
    else
      @document.entity = Entity.new
    end
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:entity_id, :scheduling_id, :operation, :total_value, :discount_value, :observation, 
        document_activities_attributes: [:id, :activity_id, :employee_id, :quantity, :unit_value, :realization, :beginning, :ending, :_destroy], 
        document_products_attributes: [:id, :product_id, :quantity, :unit_value, :_destroy])
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document_activity_fields.html.erb
<div class="row nested-fields document-activity">
    <div class="col-lg-3">
        <%= f.association :activity , :value_method => :id, :label_method => :name, :input_html => {:class => "idactivity form-control" } %>
    </div>
    <div class="col-lg-3">
    	<%= f.association :employee , :value_method => :id, :label_method => :employee_name, :input_html => {:class => "idemployee form-control" }  %>
    </div>
    <div class="col-lg-2">
        <%= f.input :unit_value, :readonly => true, :input_html => {value: f.object.unit_value.to_s, :class => "unit_value form-control", :readonly => 'readonly' }  %>
    </div>
    <div class="col-lg-2">
        <%= f.input :quantity, :input_html => {:class => "quantity form-control", value: f.object.quantity || '1', min: 1 }  %>
    </div>
	<div class="col-lg-2">
	    <%= link_to_remove_association "Remove", f, class: 'btn-rm-association btn btn-danger' %>
    </div>
</div>

app/views/documents/_document_product_fields.html.erb
<div class="row nested-fields document-product">
    <div class="col-lg-3">
        <%= f.association :product , :value_method => :id, :label_method => :name, :input_html => {:class => "idproduct form-control" } %>
    </div>
    <div class="col-lg-2">
        <%= f.input :unit_value, :readonly => true, :input_html => {:class => "unit_value form-control", :readonly => 'readonly' }  %>
    </div>
    <div class="col-lg-2">
        <%= f.input :quantity, :input_html => {:class => "quantity form-control", value: f.object.quantity || '1', min: 1 }  %>
    </div>
	<div class="col-lg-2">
        <%= link_to_remove_association "Remove", f, class: 'btn-rm-association btn btn-danger' %>
    </div>
</div>

app/views/documents/_form.html.erb
<%= simple_form_for @document, :html => { :class => 'form-horizontal', id: :document_form} do |f| %>
<div class="form-group">
  <div class="col-lg-6">
    <%= f.input :operation, :selected => 1, :input_html => {:id => "document", :class => "form-control"}  %>
    <%= error_span(@document[:operation]) %>
  </div>
  <div class="col-lg-1">
    <%= f.input :scheduling_id, :input_html => {:class => "form-control", :readonly => "readonly", :value => @document.scheduling_id}  %>:
    <%= error_span(@document[:scheduling_id]) %>
  </div>
  <div class="col-lg-5">
    <%= label_tag "Scheduling Date", nil, class: '' %>
    <%= label_tag @document.scheduling_date, nil, class: 'form-control', :readonly => "readonly" %>
  </div>
</div>
<div class="form-group">
  <div class="col-lg-6">
    <%= f.association :entity, autofocus: true, required: true, :value_method => :id, :label_method => :name, :input_html => {:id => "entity", :class => "form-control" }  %>
    <%= error_span(@document[:entity_id]) %>
  </div>

  <div class="col-sm-2">
    <%= link_to t('.new_entity', :default => t("helpers.links.new_entity")), new_entity_path, :class => 'btn btn-default btn-new-resource' %> 
  </div>
  <div class="col-sm-0 col-md-1">
    <%= label_tag "ID", nil, class: '' %>
    <%= label_tag f.object.entity_id, nil, id: "entity-id", class: 'form-control', :readonly => "readonly" %>
  </div>
  <div class="col-sm-0 col-md-3">
    <%= label_tag "E-mail", nil, class: '' %>
    <%= label_tag f.object.entity.email, nil, id: "entity-info", class: 'form-control', :readonly => "readonly" %>
  </div>
  
</div>
<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Atividades do documento
      </div>
      <div class="panel-body" id="document-activities">
        <%= f.simple_fields_for :document_activities do |document_activity| %>
        <%= render 'document_activity_fields', :f => document_activity %>
        <% end %>
        <div class="links col-sm-12">
          <%= link_to_add_association 'Add activity', f, :document_activities, class: 'btn btn-warning add-button' %>
        </div>
      </div>
      <div class="panel-heading">
        Produtos do documento
      </div>
      <div class="panel-body" id="document-products">
        <%= f.simple_fields_for :document_products do |document_product| %>
        <%= render 'document_product_fields', :f => document_product %>
        <% end %>
        <div class="links col-sm-12">
          <%= link_to_add_association 'Add product', f, :document_products, class: 'btn btn-warning add-button' %>
        </div>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-lg-4">
            <%= f.input :total_value, :input_html => { :id => "document-total-value", value: f.object.total_value || '0', min: 0, :class => "form-control"}, :readonly => true %>
            <%= error_span(@document[:total_value])%>
          </div>
          <div class="col-lg-4">
            <%= f.input :discount_value, :input_html => { :id => "document-discount-value", value: f.object.discount_value || '0', min: 0, :class => "form-control"}  %>
            <%= error_span(@document[:discount_value]) %>
          </div>
          <div class="col-lg-4">
            <%= f.input :final_value, :input_html => { :id => "document-final-value",  value: f.object.final_value, min: 0, :class => "form-control"}  %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="col-sm-12">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    documents_path, :class => 'btn btn-default' %>
  </div>
</div>
<% end %>

<script>
$(document).ready(function(){

  $('#entity').change(function () {
    var element = $(this);

    $.ajax({
      type: 'GET',
      remote: true,
      url: '/entities/' + element.val(),
      success: function(data){
        $("#entity-id").html(data.id);
        $("#entity-info").html(data.email);
      },
      error: function(data){
        console.log('error: ' + data);
        $("#entity-id").html("");
        $("#entity-info").html("");
      },
      dataType: 'JSON'
    });
  });


  $('#document-activities').on('change', '.idemployee', function () {
    var element = $(this).closest('.document-activity').find('.idactivity');
    selectActivityValue(element);
  });
  $('#document-activities').on('change', '.idactivity', function () {
    var element = $(this);

    $.ajax({
      type: 'GET',
      remote: true,
      url: '/activities/' + element.val(),
      success: function(data){
        element.closest('.document-activity').find('.quantity').val(1);
        element.closest('.document-activity').find('.unit_value').val(data.value);

        element.removeData('comissions');
        element.data('comissions', data.comissions);
        element.data('value', data.value);
        selectActivityValue(element);
        calculateValues();
      },
      error: function(data){
        console.log('error: ' + data);
      },
      dataType: 'JSON'
    });
  });

  $('#document-products').on('change', '.idproduct', function () {
    var element = $(this);
    $.ajax({
      type: 'GET',
      remote: true,
      url: '/products/' + element.val(),
      success: function(data){
        console.log(data);
        element.closest('.document-product').find('.quantity').val(1);
        element.closest('.document-product').find('.unit_value').val(data.value);
        calculateValues();
      },
      error: function(data){
        console.log('error: ' + data);
      },
      dataType: 'JSON'
    });
  });

  $('#document-discount-value').on('change', function () {
    calculateValues();
  });
  $('.btn-rm-association').on('click', function () {
    calculateValues();
  });
  $('#document-activities').bind('DOMSubtreeModified', function () {
    calculateValues();
  });
  $('#document-products').bind('DOMSubtreeModified', function () {
    calculateValues();
  });
  $('#document-activities').on('change', '.quantity', function () {
    calculateValues();
  });
  $('#document-products').on('change', '.quantity', function () {
    calculateValues();
  });

  function calculateValues(){
    var activitiesList = $("#document-activities .document-activity").map(function () {
      return this;
    }).get();
    var productsList = $("#document-products .document-product").map(function () {
      return this;
    }).get();
    
    var activitiesValue = 0;
    var productsValue = 0;

    if (activitiesList.length > 0) {
      $.each(activitiesList , function (key, item) {
        if ( $(item).is(':visible')) {
          quantity = $(item).find('.quantity').val();
          value = $(item).find('.unit_value').val();


          activitiesValue += value * quantity;
        };
      });
    };
    if (productsList.length > 0) {
      $.each(productsList , function (key, item) {
        if ( $(item).is(':visible')) {
          quantity = $(item).find('.quantity').val();
          value = $(item).find('.unit_value').val();
          productsValue += value * quantity;
        };
      });
    };

    $('#document-total-value').val(activitiesValue + productsValue);
    $('#document-final-value').val((activitiesValue + productsValue) - $('#document-discount-value').val());
  }
  
  function selectActivityValue(activity_element) {
    comissions = activity_element.data('comissions');
    employee_id = parseInt(activity_element.closest('.document-activity').find('.idemployee').val());
    has = false;
    if (comissions.length > 0 && employee_id > 0) {
      for (var i = comissions.length - 1; i >= 0; i--) {
        if (comissions[i].employee_id == employee_id) {
          activity_element.closest('.document-activity').find('.unit_value').val(comissions[i].value);
          has = true;
        }
      };
      if (!has) {
        activity_element.closest('.document-activity').find('.unit_value').val(activity_element.data('value'));
      };
    };
  }

  calculateValues();

});
</script>

app/views/documents/_menu.html.erb
<div class="page-header row">
  <div  class="page-title col-sm-12 col-md-3">
    <h3><%=t '.title', :default => title, :model => model_name %></h3>
  </div>
  <div class="col-sm-6 col-md-4 btn-group" role="group">
    <span class="btn disabled">Options</span>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_document_path, :class => 'btn btn-primary' unless action == "new"%>

    <%= link_to t('.list', :default => t("list")),
    documents_path, :class => 'btn btn-default' unless action == "index" %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_document_path(@document), :class => 'btn btn-default'  if action == "show"  %>

  </div>
  <% if action == "index" %>
  <div class="col-sm-6 col-md-5">
    <nav>
      <ul class="nav nav-justified">
        <li class="<%= @active_all %>"><a href="<%= documents_path %>">All Documents</a></li>
        <li class="<%= @active_pending %>"><a href="<%= pending_documents_path %>">Pending</a></li>
        <li class="<%= @active_payed %>"><a href="<%= payed_documents_path %>">Payed</a></li>
      </ul>
    </nav>
  </div>
  <% end %>

</div>

app/views/documents/edit.html.erb
<%- model_class = Document -%>
<%= render "menu", action: "edit", title: [:'helpers.titles.edit', 'Edit %{model}'], :model_name => model_class.model_name.human.titleize  %>

<%= render :partial => 'form' %>

app/views/documents/index.html.erb
<%- model_class = Document -%>
<%= render "menu", action: "index", title: model_class.model_name.human.pluralize.titleize, model_name: model_class %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:entity_id) %></th>
      <th><%= model_class.human_attribute_name(:scheduling_id) %></th>
      <th><%= model_class.human_attribute_name(:final_value) %></th>
      <th><%= model_class.human_attribute_name(:received_value) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document| %>
    <tr>
      <td><%= link_to document.id, document_path(document), :class => 'btn btn-xs btn-default'  %></td>
      <td><%= document.entity.name %></td>
      <td><%= document.scheduling_date %></td>
      <td><%= (document.discount_value.nil?) ? document.total_value : document.total_value - document.discount_value  %></td>
      <td><%= document.received_value %></td>
      <td><%=l document.created_at %></td>
      <td>
        <%= link_to t('.new_acquittance', :default => t("helpers.links.new_acquittance")),
        new_document_acquittance_path(document.id), :class => 'btn btn-success btn-xs' %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_document_path(document), :class => 'btn btn-default btn-xs' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/documents/new.html.erb
<%- model_class = Document -%>
<%= render "menu", action: "new", title: [:'helpers.titles.new', 'New %{model}'], :model_name => model_class.model_name.human.titleize  %>
<%= render :partial => 'form' %>

app/views/documents/show.html.erb
<%- model_class = Document -%>

<%= render "menu", action: "show", title: model_class.model_name.human.titleize, :model_name => model_class.model_name.human.titleize  %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:entity_id) %>:</strong></dt>
  <dd><%= @document.entity_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scheduling_id) %>:</strong></dt>
  <dd><%= @document.scheduling_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:operation) %>:</strong></dt>
  <dd><%= @document.operation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:total_value) %>:</strong></dt>
  <dd><%= @document.total_value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:discount_value) %>:</strong></dt>
  <dd><%= @document.discount_value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:observation) %>:</strong></dt>
  <dd><%= @document.observation %></dd>
</dl>