config/routes.rb
Rails.application.routes.draw do

  resources :notifications , except: [:destroy, :edit, :update]
  resources :employees
  resources :activities
  resources :products
  resources :schedulings do
    collection do
      get 'todaypending'
      get 'today'
    end
  end

  resources :documents  do 
    collection do
      get 'pending'
      get 'payed'
      get 'with_received'
    end
  end  
  resources :acquittances do
    collection do
      get 'today'
    end
  end

  authenticated :user do
    resources :entities, only: [:new, :create, :edit, :update, :destroy]
    root to: 'entities#index', as: :authenticated_root
  end
  resources :entities, only: [:index, :show]
  root to: redirect('/users/sign_in')


  devise_for :users, 
  :controllers => { registrations: 'registrations' }, 
  :path_names => {:sign_up => 'register'}
  devise_scope :user do
    get "users/register(/:entity_id)", :to => "registrations#new", as: :new_entity_user
  end


  # controller :registrations do 
  # end
  controller :employees do 
    get 'employees/new(/:entity_id)' => :new, as: :new_entity_employee
  end
  controller :documents do 
    get 'documents/new(/:scheduling_id)' => :new, as: :new_scheduling_document
  end
  controller :acquittances do 
    get 'acquittances/new(/:document_id)' => :new, as: :new_document_acquittance
  end
  controller :notifications do 
    get 'schedulings/:scheduling_id/notifications/new' => :new, as: :new_scheduling_notification
    get 'notifications/:id/resend/' => :resend, as: :notification_resend
  end


end

app/models/scheduling.rb
class Scheduling < ActiveRecord::Base
  belongs_to :entity
  belongs_to :activity
  belongs_to :employee
  belongs_to :scheduling_status

  has_one :document
  has_many :notifications

  validate :picked_moment, on: :create
  validate :available_moment, on: :update

  validates :entity_id, presence: true
  validates :employee_id, presence: true
  validates :dtt_moment, presence: true, allow_blank: false

  scope :today, ->{where("DATE(dtt_moment) = DATE(NOW())")}
  scope :status, ->(status) {where("scheduling_status_id = ?", status)}
  scope :pending, ->{where("scheduling_status_id != 2 AND scheduling_status_id != 4")}

  def picked_moment
    errors.add(:dtt_moment, "Date already Picked") if Scheduling.where("employee_id = ? AND dtt_moment = ?", self.employee_id, self.dtt_moment).any?
  end
  def available_moment
		errors.add(:dtt_moment, "Date already Picked") if Scheduling.where("employee_id = ? AND dtt_moment = ? AND id <> ?", self.employee_id, self.dtt_moment, self.id).any?
  end

end

app/controllers/schedulings_controller.rb
class SchedulingsController < ApplicationController
  before_action :set_scheduling, only: [:show, :edit, :update, :destroy]

  # GET /schedulings
  # GET /schedulings.json
  def index
    @schedulings = Scheduling.all
    @active_all = "active"
  end
  
  def today
    @schedulings = Scheduling.today
    @active_alltoday = "active"
    render action: :index
  end
  def todaypending
    @schedulings = Scheduling.today.pending
    @active_pendingtoday = "active"
    render action: :index
  end

  # GET /schedulings/1
  # GET /schedulings/1.json
  def show
    @scheduling.build_entity
  end

  # GET /schedulings/new
  def new
    @scheduling = Scheduling.new
  end

  # GET /schedulings/1/edit
  def edit
  end

  # POST /schedulings
  # POST /schedulings.json
  def create
    @scheduling = Scheduling.new(scheduling_params)

    respond_to do |format|
      if @scheduling.save
        format.html { redirect_to @scheduling, notice: 'Scheduling was successfully created.' }
        format.json { render :show, status: :created, location: @scheduling }
      else
        format.html { render :new }
        format.json { render json: @scheduling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedulings/1
  # PATCH/PUT /schedulings/1.json
  def update
    respond_to do |format|
      if @scheduling.update(scheduling_params)
        format.html { redirect_to @scheduling, notice: 'Scheduling was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduling }
      else
        format.html { render :edit }
        format.json { render json: @scheduling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedulings/1
  # DELETE /schedulings/1.json
  def destroy
    @scheduling.destroy
    respond_to do |format|
      format.html { redirect_to schedulings_url, notice: 'Scheduling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduling
      @scheduling = Scheduling.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduling_params
      params.require(:scheduling).permit(:entity_id, :activity_id, :employee_id, :dtt_moment, :t_end, :scheduling_status_id,:observation)
    end
end

app/helpers/schedulings_helper.rb
module SchedulingsHelper
	def status_tag status
		unless status.blank?
			color = status_color status.id
			"<span class='label label-#{color}'>#{status.title}</span>".html_safe
		end
	end

	def status_color status_id
		case status_id # a_variable is the variable we want to compare
			when 1 
			 "success" 
			when 2  
				"danger"
			when 3  
			  "info"
			else 
			  "default"
			end
	end
end

app/views/schedulings/_form.html.erb
<%= simple_form_for @scheduling, :html => { :class => 'form-horizontal' } do |f| %>
<div class="form-group">
  <div class="col-sm-11 col-md-6">
    <%= f.association :entity , autofocus: true, required: true, :value_method => :id, :label_method => :name, :input_html => {:id => "entity", :class => "form-control"} %> 
    <%= error_span(@scheduling[:entity_id]) %>
  </div>

  <div class="col-sm-2">
    <%= link_to t('.new_entity', :default => t("helpers.links.new_entity")), new_entity_path, :class => 'btn btn-default btn-new-resource' %> 
  </div>
  <div class="col-sm-0 col-md-1">
    <%= label_tag "ID", nil, class: ''%>
    <%= label_tag "", nil, id: "entity-id" , class: 'form-control', :readonly => "readonly" %>
  </div>
  <div class="col-sm-0 col-md-3">
    <%= label_tag "E-mail", nil, class: '' %>
    <%= label_tag "", nil, id: "entity-info", class: 'form-control', :readonly => "readonly" %>
  </div>

</div>
<div class="form-group">
  <div class="col-sm-12 col-md-6">
    <%= f.association :activity, required: true, :value_method => :id, :label_method => :name, :input_html => {:id => "activity", :class => "form-control", 'data-comissions' => ''}  %>
    <%= error_span(@scheduling[:activity_id]) %>
  </div>

  <div class="col-sm-0 col-lg-1 col-md-offset-2">
    <%= label_tag "ID", nil, class: '' %>
    <%= label_tag "", nil, id: "activity-id", class: 'form-control', :readonly => "readonly" %>
  </div>
  <div class="col-sm-0 col-lg-3">
    <%= label_tag "Value", nil, class: '' %>
    <%= label_tag "", nil, id: "activity-info", class: 'form-control', :readonly => "readonly" %>
  </div>

</div>
<div class="form-group">
  <div class="col-sm-12 col-md-6">
    <%= f.association :employee, required: true, :value_method => :id, :label_method => :employee_name, :input_html => {:id => "employee", :class => "form-control"}  %>
    <%= error_span(@scheduling[:employee_id]) %>
  </div>

  <div class="col-sm-0 col-lg-1 col-md-offset-2">
    <%= label_tag "ID", nil, class: '' %>
    <%= label_tag "", nil, id: "employee-id", class: 'form-control', :readonly => "readonly" %>
  </div>
  <div class="col-sm-0 col-lg-3">
    <%= label_tag "Function", nil, class: '' %>
    <%= label_tag "", nil, id: "employee-info", class: 'form-control', :readonly => "readonly" %>
  </div>

</div>
<div class="form-group">
  <div class="col-sm-12 col-md-6">
    <%= f.input :dtt_moment, wrapper: :horizontal_select_date, :input_html => {:class => "form-control"} %>
    <%= error_span(@scheduling[:dtt_moment]) %>
  </div>
  <div class="col-sm-12 col-md-6">
    <%= f.input :t_end, wrapper: :horizontal_select_date, :input_html => {:class => "form-control"} %>
    <%= error_span(@scheduling[:t_end]) %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-12">
    <%= f.input :observation, :input_html => {:class => "form-control", :rows =>3} %>
    <%= error_span(@scheduling[:observation]) %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-12">
   <%= f.association :scheduling_status, :selected => 1, required: true, :value_method => :id, :label_method => :title, :input_html => {:id => "status", :class => "form-control"}  %>
   <%= error_span(@scheduling[:id_scheduling_status]) %>
 </div>
</div>
<div class="form-group">
  <div class="col-sm-12">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
</div>

<% end %>



<script>
$(document).ready(function(){
  $('#entity').change(function () {
    var element = $(this);

    if ($(this).val() != '') 
      $.ajax({
        type: 'GET',
        remote: true,
        url: '/entities/' + element.val(),
        success: function(data){
          $("#entity-id").html(data.id);
          $("#entity-info").html(data.email);
        },
        error: function(data){
          console.log('error: ' + data);
          $("#entity-id").html("");
          $("#entity-info").html("");
        },
        dataType: 'JSON'
      });
  });

  $('#activity').change(function () {
    var element = $(this);

    if ($(this).val() != '') 
      $.ajax({
        type: 'GET',
        remote: true,
        url: '/activities/' + element.val(),
        success: function(data){
          $("#activity-id").html(data.id);
          $("#activity-info").html(data.value);
          element.removeData('comissions');
          element.data('comissions', data.comissions);
          element.data('value', data.value);
          selectActivityValue();
        },
        error: function(data){
          console.log('error: ' + data);
          $("#activity-id").html("");
          $("#activity-info").html("");
        },
        dataType: 'JSON'
      });
  });

  $('#employee').change(function () {
    var element = $(this);
    if ($(this).val() != '') 
      $.ajax({
        type: 'GET',
        remote: true,
        url: '/employees/' + element.val(),
        success: function(data){
          $("#employee-id").html(data.id);
          $("#employee-info").html(data.function);
          selectActivityValue();

        },
        error: function(data){
          console.log('error: ' + data);
          $("#employee-id").html("");
          $("#employee-info").html("");
        },
        dataType: 'JSON'
      });
  });

  function selectActivityValue() {
    comissions = $('#activity').data('comissions');
    employee_id = parseInt($('#employee').val());
    has = false;
    if (comissions.length > 0 && employee_id > 0) {
      for (var i = comissions.length - 1; i >= 0; i--) {
        if (comissions[i].employee_id == employee_id) {
          $("#activity-info").html(comissions[i].value)
          has = true;
        }
      };
      if (!has) {
        $("#activity-info").html($('#activity').data('value'));
      };
    };
  }
});
</script>

app/views/schedulings/_menu.html.erb
<div class="page-header row">
  <div  class="page-title col-sm-12 col-md-3">
    <h3><%=t '.title', :default => title, :model => model_name %></h3>
  </div>
  <div class="col-sm-6 col-md-4 btn-group" role="group">
    <span class="btn disabled">Options</span>
    <%= link_to t('.new', :default => t("helpers.links.new")), new_scheduling_path, :class => 'btn btn-primary' unless action == "new"%>

    <%= link_to t('.list', :default => t("list")),
    schedulings_path, :class => 'btn btn-default' unless action == "index" %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
    edit_scheduling_path(@scheduling), :class => 'btn btn-default'  if action == "show"  %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    scheduling_path(@scheduling),
    :method => 'delete',
    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
    :class => 'btn btn-danger' if action == "show"%>
  </div>
  <% if action == "index" %>
  <div class="col-sm-6 col-md-5">
    <nav>
      <ul class="nav nav-justified">
        <li class="<%= @active_pendingtoday %>"><a href="<%= todaypending_schedulings_path %>">Pending Today</a></li>
        <li class="<%= @active_alltoday %>"><a href="<%= today_schedulings_path %>">All Today</a></li>
        <li class="<%= @active_all %>"><a href="<%= schedulings_path %>">All</a></li>
      </ul>
    </nav>
  </div>
  <% end %>

</div>

app/views/schedulings/edit.html.erb
<%- model_class = Scheduling -%>
<%= render "menu", action: "edit", title: [:'helpers.titles.edit', 'Edit %{model}'], :model_name => model_class.model_name.human.titleize  %>
<%= render :partial => 'form' %>

app/views/schedulings/index.html.erb
<%- model_class = Scheduling -%>
<%= render "menu", action: "index", title: model_class.model_name.human.pluralize.titleize, model_name: model_class %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:entity_id) %></th>
      <th><%= model_class.human_attribute_name(:activity_id) %></th>
      <th><%= model_class.human_attribute_name(:employee_id) %></th>
      <th><%= model_class.human_attribute_name(:dtt_moment) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @schedulings.each do |scheduling| %>
      <tr>
        <td><%= link_to scheduling.id, scheduling_path(scheduling), :class => 'btn btn-xs btn-default' %></td>
        <td><%= status_tag scheduling.scheduling_status %></td>
        <td><%= scheduling.entity.name %></td>
        <td><%= scheduling.activity.name %></td>
        <td><%= scheduling.employee.entity.name %></td>
        <td><%= scheduling.dtt_moment %></td>
        <td>
          <%= link_to "Notify", new_scheduling_notification_path(scheduling.id), :class => 'btn btn-warning btn-xs' %>
          <%= link_to "Make Document", new_scheduling_document_path(scheduling.id), :class => 'btn btn-success btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_scheduling_path(scheduling), :class => 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/schedulings/new.html.erb
<%- model_class = Scheduling -%>
<%= render "menu", action: "new", title: [:'helpers.titles.new', 'New %{model}'], :model_name => model_class.model_name.human.titleize  %>
<%= render :partial => 'form' %>

app/views/schedulings/show.html.erb
<%- model_class = Scheduling -%>
<%= render "menu", action: "show", title: model_class.model_name.human.titleize, :model_name => model_class.model_name.human.titleize  %>

<div class="col-md-6">
  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:entity_id) %>:</strong></dt>
    <dd><%= @scheduling.entity_id %></dd>
    <dt><strong><%= model_class.human_attribute_name(:activity_id) %>:</strong></dt>
    <dd><%= @scheduling.activity_id %></dd>
    <dt><strong><%= model_class.human_attribute_name(:employee_id) %>:</strong></dt>
    <dd><%= @scheduling.employee_id %></dd>
    <dt><strong><%= model_class.human_attribute_name(:dtt_moment) %>:</strong></dt>
    <dd><%= @scheduling.dtt_moment %></dd>
    <dt><strong><%= model_class.human_attribute_name(:t_end) %>:</strong></dt>
    <dd><%= @scheduling.t_end %></dd>
    <dt><strong><%= model_class.human_attribute_name(:scheduling_status_id) %>:</strong></dt>
    <dd><%= @scheduling.scheduling_status_id %></dd>
    <dt><strong><%= model_class.human_attribute_name(:observation) %>:</strong></dt>
    <dd><%= @scheduling.observation %></dd>
  </dl>
</div>

<div class="col-md-6">
  <div class="panel panel-warning">
    <div class="panel-heading">
      Scheduling notifications
    </div>
    <ul class="list-group">
      <li class="list-group-item">
        <%= link_to "Send a notification", new_scheduling_notification_path(@scheduling.id), class: "btn btn-warning" %>
      </li>
    </ul>
  </div>
</div>