config/routes.rb
Rails.application.routes.draw do

  resources :notifications , except: [:destroy, :edit, :update]
  resources :employees
  resources :activities
  resources :products
  resources :schedulings do
    collection do
      get 'todaypending'
      get 'today'
    end
  end

  resources :documents  do 
    collection do
      get 'pending'
      get 'payed'
      get 'with_received'
    end
  end  
  resources :acquittances do
    collection do
      get 'today'
    end
  end

  authenticated :user do
    resources :entities, only: [:new, :create, :edit, :update, :destroy]
    root to: 'entities#index', as: :authenticated_root
  end
  resources :entities, only: [:index, :show]
  root to: redirect('/users/sign_in')


  devise_for :users, 
  :controllers => { registrations: 'registrations' }, 
  :path_names => {:sign_up => 'register'}
  devise_scope :user do
    get "users/register(/:entity_id)", :to => "registrations#new", as: :new_entity_user
  end


  # controller :registrations do 
  # end
  controller :employees do 
    get 'employees/new(/:entity_id)' => :new, as: :new_entity_employee
  end
  controller :documents do 
    get 'documents/new(/:scheduling_id)' => :new, as: :new_scheduling_document
  end
  controller :acquittances do 
    get 'acquittances/new(/:document_id)' => :new, as: :new_document_acquittance
  end
  controller :notifications do 
    get 'schedulings/:scheduling_id/notifications/new' => :new, as: :new_scheduling_notification
    get 'notifications/:id/resend/' => :resend, as: :notification_resend
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Agenda</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-primary navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Trend<span>Hair</span></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Entities", entities_path %></li>
              <li><%= link_to "Schedulings", schedulings_path %></li>
              <li><%= link_to "Notifications", notifications_path %></li>
              <li><%= link_to "Documents", documents_path %></li>
              <li><%= link_to "Acquittances", acquittances_path %></li>
              <li class="dropdown-toggleopdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Configurations<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Employees", employees_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Activities", activities_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Products", products_path %></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.entity.blank? ? current_user.email : current_user.entity.name %> <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Editar seus dados", edit_user_registration_path %></li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
              <%end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        <div class="row">
          <%= bootstrap_flash %>
        </div>
        <div class="row-fluid">
          <%= yield %>
        </div>  
      </div><!--/row-->
    </main>
    <footer>
    </footer>

  </body>
</html>